MA-21719 Add kernel_config_v_6.6
"kernel_config_v_6.6" is defined in ${ANDROID}/kernel/configs.

Add it to fix build error:

ERROR: files are incompatible: Runtime info and
framework compatibility matrix are incompatible: No kernel entry found
for kernel version 6.6 at kernel FCM version 8.

Change-Id: I6c2ebf111f2bfddb7d6d24417ad3a915f3f7e97b
Signed-off-by: Zhipeng Wang <zhipeng.wang_1@nxp.com>
Reviewed-on: http://androidsource.nxp.com/project/23697