MA-22984-1 Add "framework_compatibility_matrix.202504.xml"
Fix build error when "make" or "m":
All HALs in device manifest are declared in FCM <= level 202404
ERROR: files are incompatible: Runtime info and framework
compatibility matrix are incompatible: No kernel entry found for
kernel version 6.12 at kernel FCM version 202504.

Change-Id: I1bf7ded46d214a991b4079afcd6c8750c07743fc
Signed-off-by: Jindong Yue <jindong.yue@nxp.com>
Reviewed-on: http://androidsource.nxp.com/project/27804
Reviewed-by: Zhipeng Wang <zhipeng.wang_1@nxp.com>