MA-22692 remove camera.device-external-imx-impl from default list
Since the camera.device-external-imx-impl is handled by
imx_external_camera_aidl.go, so remove the
camera.device-external-imx-impl from the default dependency to fix the
trout build error:
error: hardware/interfaces/camera/provider/default/Android.bp:49:1:
module "android.hardware.camera.provider-V1-external-impl" variant
"android_vendor_arm64_armv8-a_cortex-a53_shared": depends on disabled
module "camera.device-external-imx-impl"

Change-Id: I422dc9a9a320f78f626baf1521067101028199bd
Signed-off-by: Haoran Wang <elven.wang@nxp.com>
Reviewed-on: http://androidsource.nxp.com/project/29074
Reviewed-by: Hui Fang <hui.fang@nxp.com>